In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup as bs
import time

In [ ]:
start = time.time()
url = 'https://www.investing.com/stock-screener/Service/SearchStocks'

header = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/79.0.3945.130 Safari/537.36',
    'X-Requested-With': 'XMLHttpRequest'
}

payload = {
    'country[]': '5',  ## US-country code
    'sector': '7,5,12,3,8,9,1,6,2,4,10,11', ## all sectors
    'industry': '81,56,59,41,68,67,88,51,72,47,12,8,50,2,71,9,69,45,46,13,94,102,95,58,100,101,87,31,6,38,79,30,77,'
                '28,5,60,18,26,44,35,53,48,49,55,78,7,86,10,1,34,3,11,62,16,24,20,54,33,83,29,76,37,90,85,82,22,14,'
                '17,19,43,89,96,57,84,93,27,74,97,4,73,36,42,98,65,70,40,99,39,92,75,66,63,21,25,64,61,32,91,52,23,'
                '15,80', ## all industries
    'equityType': 'ORD,DRC,Preferred,Unit,ClosedEnd,REIT,ELKS,OpenEnd,Right,ParticipationShare,CapitalSecurity,'
                  'PerpetualCapitalSecurity,GuaranteeCertificate,IGC,Warrant,SeniorNote,Debenture,ETF,ADR,ETC,ETN',
    'pn': 1,
    'order[col]': 'eq_market_cap',
    'order[dir]': 'd'
}

def run(pages):
    json_list = []
    for i in range(1, pages):
        try:
            payload['pn'] = i
            req_time = time.time()
            req = requests.post(url, data = payload, headers = header).json()
            req_end = time.time()
            print('소요시간 {}초'.format((req_end-req_time)/60))
            print('남은 페이지 수 : {}개'.format(pages - i))   
            json_list += req['hits']
        except Exception as e:
            print(e)
            
    df = pd.DataFrame(json_list)
    return df

pages = int(10914/50) + 1
df = run(pages)

end = time.time()
print('{}분'.format((end-start)/60))

소요시간 0.03306211630503337초
남은 페이지 수 : 218개
소요시간 0.030517876148223877초
남은 페이지 수 : 217개
소요시간 0.037632922331492104초
남은 페이지 수 : 216개
소요시간 0.03033530314763387초
남은 페이지 수 : 215개
소요시간 0.030785266558329263초
남은 페이지 수 : 214개
소요시간 0.03606930573781331초
남은 페이지 수 : 213개
소요시간 0.03460739850997925초
남은 페이지 수 : 212개
소요시간 0.03580445051193237초
남은 페이지 수 : 211개
소요시간 0.031067105134328206초
남은 페이지 수 : 210개
소요시간 0.030041984717051187초
남은 페이지 수 : 209개
소요시간 0.03015298048655192초
남은 페이지 수 : 208개
소요시간 0.03159875472386678초
남은 페이지 수 : 207개
소요시간 0.0349287470181783초
남은 페이지 수 : 206개
소요시간 0.03177058299382528초
남은 페이지 수 : 205개
소요시간 0.03522232373555501초
남은 페이지 수 : 204개
소요시간 0.03567248582839966초
남은 페이지 수 : 203개
소요시간 0.030070261160532633초
남은 페이지 수 : 202개
소요시간 0.02964690128962199초
남은 페이지 수 : 201개
소요시간 0.032230472564697264초
남은 페이지 수 : 200개
소요시간 0.02993663152058919초
남은 페이지 수 : 199개
소요시간 0.03208365043004354초
남은 페이지 수 : 198개
소요시간 0.034368932247161865초
남은 페이지 수 : 197개
소요시간 0.030856200059254966초
남은 페이지 수 : 196개
소요시간 0.03459177414576212초
남은 페이지 수 : 195개
소요시간 0.035903783639272054초
남은 페이지 수 : 194개
소요시간 0.02997984488805135초
남은 페이지 수 : 193개
소요시간 0.030495580037434897초
남은 페이지 수 : 192개
소요시간 0.029884926478068032초
남은 페이지 수 : 191개
소요시간 0.031116751829783122초
남은 페이지 수 : 190개
소요시간 0.031007015705108644초
남은 페이지 수 : 189개
소요시간 0.03522251447041829초
남은 페이지 수 : 188개
소요시간 0.03125973145167033초
남은 페이지 수 : 187개
소요시간 0.03124978542327881초
남은 페이지 수 : 186개
소요시간 0.032397524515787764초
남은 페이지 수 : 185개
소요시간 0.03136622508366903초
남은 페이지 수 : 184개
소요시간 0.030983281135559083초
남은 페이지 수 : 183개
소요시간 0.03038582404454549초
남은 페이지 수 : 182개
소요시간 0.030779067675272623초
남은 페이지 수 : 181개
소요시간 0.031144070625305175초
남은 페이지 수 : 180개
소요시간 0.031116247177124023초
남은 페이지 수 : 179개
소요시간 0.030428107579549155초
남은 페이지 수 : 178개
소요시간 0.0350472887357076초
남은 페이지 수 : 177개
소요시간 0.030086215337117514초
남은 페이지 수 : 176개
소요시간 0.03518991072972615초
남은 페이지 수 : 175개
소요시간 0.031133206685384114초
남은 페이지 수 : 174개
소요시간 0.03211409250895182초
남은 페이지 수 : 173개
소요시간 0.035189322630564374초
남은 페이지 수 : 172개
소요시간 0.032892855008443196초
남은 페이지 수 : 171개
소요시간 0.03535545269648234초
남은 페이지 수 : 170개
소요시간 0.031548961003621416초
남은 페이지 수 : 169개
소요시간 0.03066856066385905초
남은 페이지 수 : 168개
소요시간 0.0357039213180542초
남은 페이지 수 : 167개

In [10]:
df

,pair_ID,stock_symbol,parent_pair_ID,canonical_to_pair_id,override_country_ID,eq_pe_ratio,eq_pe_ratio_eu,eq_market_cap,eq_market_cap_eu,eq_one_year_return,...,tech_sum_month_constant,daily,daily_eu,daily_frmt,aintcov,aintcov_eu,aintcov_us,ttmintcov,ttmintcov_eu,ttmintcov_us
0,252,MSFT,0,0,0,34.91,"34,91",1400000000000,"1,40T",78.57,...,Strong Buy,-2.27,"-2,27",-2.27,NaN,NaN,NaN,NaN,NaN,NaN
1,6408,AAPL,0,0,0,25.40,"25,4",1400000000000,"1,40T",88.69,...,Strong Buy,-0.61,"-0,61",-0.61,NaN,NaN,NaN,NaN,NaN,NaN
2,6435,AMZN,0,0,0,92.71,"92,71",1070000000000,"1,07T",34.36,...,Strong Buy,0.83,"0,83",0.83,18.93359,"18,93",18.93,18.95698,"18,96",18.96
3,100160,GOOG,0,0,0,30.68,"30,68",1040000000000,"1,04T",37.77,...,Strong Buy,0.00,"0,00",0.00,NaN,NaN,NaN,NaN,NaN,NaN
4,6369,GOOGL,0,0,0,30.68,"30,68",1040000000000,"1,04T",36.85,...,Strong Buy,0.04,"0,04",0.04,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,52315,NUTTQ,0,0,0,NaN,NaN,47620,"47,62K",-38.10,...,Strong Sell,0.00,"0,00",0.00,-0.06612,"-0,07",-0.07,-0.06612,"-0,07",-0.07
9996,15812,CRMBQ,0,0,0,NaN,NaN,47600,"47,60K",-19.15,...,Strong Sell,0.00,"0,00",0.00,-35.48604,"-35,49",-35.49,-26.38950,"-26,39",-26.39
9997,51516,CBLRF,0,0,0,NaN,NaN,46870,"46,87K",0.00,...,Strong Sell,0.00,"0,00",0.00,-31.15266,"-31,15",-31.15,-32.44082,"-32,44",-32.44
9998,961113,CWRL,0,0,0,NaN,NaN,46550,"46,55K",-90.00,...,NaN,0.00,"0,00",0.00,-3.59352,"-3,59",-3.59,-3.08104,"-3,08",-3.08
9999,1136269,XCRP,0,0,0,NaN,NaN,46370,"46,37K",0.00,...,Sell,0.00,"0,00",0.00,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
x = df.copy()
x.set_index('stock_symbol',inplace=True)

stock_symbol,MSFT,AAPL,AMZN,GOOG,GOOGL,FB,CCI_pa,BABA,BRKa,BRKb,...,HRAA,DRGV,DIRV,FCTOA,AVTI,NUTTQ,CRMBQ,CBLRF,CWRL,XCRP
pair_ID,252,6408,6435,100160,6369,26490,959747,941155,20562,13834,...,50901,51456,51659,51379,51239,52315,15812,51516,961113,1136269
parent_pair_ID,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
canonical_to_pair_id,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
override_country_ID,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
eq_pe_ratio,34.91,25.4,92.71,30.68,30.68,35,77.07,25.94,20.87,20.87,...,NaN,0.12,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
aintcov_eu,NaN,NaN,"18,93",NaN,NaN,NaN,"2,33",NaN,"1,14","1,14",...,"-6,86","126,18","-0,39","-4,94",NaN,"-0,07","-35,49","-31,15","-3,59",NaN
aintcov_us,NaN,NaN,18.93,NaN,NaN,NaN,2.33,NaN,1.14,1.14,...,-6.86,126.18,-0.39,-4.94,NaN,-0.07,-35.49,-31.15,-3.59,NaN
ttmintcov,NaN,NaN,18.95698,NaN,NaN,NaN,2.46041,NaN,48.45923,48.45923,...,NaN,87.48576,-1.01221,-3.42142,-1.81807,-0.06612,-26.38950,-32.44082,-3.08104,NaN
ttmintcov_eu,NaN,NaN,"18,96",NaN,NaN,NaN,"2,46",NaN,"48,46","48,46",...,NaN,"87,49","-1,01","-3,42","-1,82","-0,07","-26,39","-32,44","-3,08",NaN
ttmintcov_us,NaN,NaN,18.96,NaN,NaN,NaN,2.46,NaN,48.46,48.46,...,NaN,87.49,-1.01,-3.42,-1.82,-0.07,-26.39,-32.44,-3.08,NaN

In [ ]:
x.T

In [14]:
result = x.T.iloc[0]

In [15]:
result

stock_symbol
MSFT         252
AAPL        6408
AMZN        6435
GOOG      100160
GOOGL       6369
          ...
NUTTQ      52315
CRMBQ      15812
CBLRF      51516
CWRL      961113
XCRP     1136269
Name: pair_ID, Length: 10000, dtype: object

In [17]:
result.to_pickle("../Database/us_pair_id.pickle")

In [18]:
stock_url = 'https://www.investing.com/instruments/HistoricalDataAjax'

In [21]:
pair_id = 8127
ticker = 'VZ'
st_date = '01/12/2020'
end_date = '02/12/2020'

payload_stock = {
    'curr_id': pair_id, # 8127
    'header': ticker + ' Historical Data', # VZ
    'st_date': st_date, # 01/12/2020
    'end_date': end_date, # 02/12/2020
    'interval_sec': 'Daily',
    'sort_col': 'date',
    'sort_ord': 'DESC',
    'action': 'historical_data'
}

req = requests.post(stock_url, data=payload_stock, headers=header).text
table = pd.read_html(req)[1]
table

,0,1,2,3,4
0,Highest: 61.00,Lowest: 57.65,Difference: 3.35,Average: 59.59,Change %: -0.51

In [43]:
st = time.time()
tickers = list(result.index)
tables = []
for idx,ticker in enumerate(tickers):
    pair_id = result.loc[ticker]
    payload_stock['curr_id'] = pair_id
    payload_stock['header'] = ticker + ' Historical Data'
    req = requests.post(stock_url, data=payload_stock, headers=header).text
    soup = bs(req, 'lxml').find('table')
    tables.append(str(soup))
    if idx==30:
        break

linked_table = " ".join(tables)
table = pd.read_html(linked_table)
end = time.time()
print(end-st)

22.358204126358032

In [42]:
table[1]

            Date   Price    Open    High     Low    Vol. Change %
0   Feb 11, 2020  319.61  323.51  323.88  318.74  23.58M   -0.60%
1   Feb 10, 2020  321.55  314.18  321.55  313.85  27.34M    0.47%
2   Feb 07, 2020  320.03  322.37  323.40  318.00  29.42M   -1.59%
3   Feb 06, 2020  325.21  322.57  325.22  320.26  26.36M    1.17%
4   Feb 05, 2020  321.45  323.52  324.76  318.95  29.71M    0.82%
5   Feb 04, 2020  318.85  315.31  319.64  313.63  34.15M    3.30%
6   Feb 03, 2020  308.66  304.30  313.49  302.22  43.50M   -0.27%
7   Jan 31, 2020  309.51  320.93  322.68  308.29  49.90M   -4.43%
8   Jan 30, 2020  323.87  320.54  324.09  318.75  31.69M   -0.14%
9   Jan 29, 2020  324.34  324.45  327.85  321.38  54.15M    2.09%
10  Jan 28, 2020  317.69  312.60  318.40  312.19  40.56M    2.83%
11  Jan 27, 2020  308.95  310.06  311.77  304.88  40.49M   -2.94%
12  Jan 24, 2020  318.31  320.25  323.33  317.52  36.63M   -0.29%
13  Jan 23, 2020  319.23  317.92  319.56  315.65  26.12M    0.48%
14  Jan 22, 2020  317.70  318.58  319.99  317.31  25.46M    0.36%
15  Jan 21, 2020  316.57  317.19  319.02  316.00  27.71M   -0.68%
16  Jan 17, 2020  318.73  316.27  318.74  315.00  34.45M    1.11%
17  Jan 16, 2020  315.24  313.59  315.70  312.09  27.21M    1.25%
18  Jan 15, 2020  311.34  311.85  315.50  309.55  30.48M   -0.43%
19  Jan 14, 2020  312.68  316.70  317.57  312.17  40.65M   -1.35%
20  Jan 13, 2020  316.96  311.64  317.07  311.15  30.52M    2.14%

In [ ]:
st = time.time()
stock_url = 'https://www.investing.com/instruments/HistoricalDataAjax'
pair_id = 8127
ticker = 'VZ'
st_date = '01/12/2020'
end_date = '02/12/2020'

payload_stock = {
    'curr_id': pair_id, # 8127
    'header': ticker + ' Historical Data', # VZ
    'st_date': st_date, # 01/12/2020
    'end_date': end_date, # 02/12/2020
    'interval_sec': 'Daily',
    'sort_col': 'date',
    'sort_ord': 'DESC',
    'action': 'historical_data'
}


tickers = list(result.index)
tables = []
for idx,ticker in enumerate(tickers):
    pair_id = result.loc[ticker]
    payload_stock['curr_id'] = pair_id
    payload_stock['header'] = ticker + ' Historical Data'
    req = requests.post(stock_url, data=payload_stock, headers=header).text
    soup = bs(req, 'lxml').find('table')
    tables.append(str(soup))
    if idx==30:
        break

linked_table = " ".join(tables)
table = pd.read_html(linked_table)
end = time.time()
print(end-st)

In [83]:
from datetime import datetime

In [95]:
url = 'https://advcharts.investing.com/advinion2016/advanced-charts/1/1/8/GetRecentHistory'
payload = {
    'strSymbol': '43433',
    'iTop': '1500',
    'strPriceType': 'bid',
    'strFieldsMode': 'allFields',
    'strExtraData': 'lang_ID=1',
    'strTimeFrame': '5M'
}

header = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36'
}

In [93]:
while True:
    wait_time = 60 - datetime.now().second
    time.sleep(wait_time)
    req = requests.get(url, params=payload, headers=header).text
    latest = json.loads(req)['data'][-1]
    latest_df = pd.DataFrame([latest])
    now_minute = datetime.now().minute
    print(latest_df)
    time.sleep(60)

                  date   open  close    low   high  volume  volume_ac  \
0  2020-02-12 04:55:00  60300  60400  60300  60400  123915    9128413

   volume_open related_ec_event_id related_news_items  start_timestamp split  \
0      9004498                None               None       1581483300  None

  dividend related_patterns_high related_patterns_med
0     None                  None                 None
                  date   open  close    low   high  volume  volume_ac  \
0  2020-02-12 04:55:00  60300  60400  60300  60400  135106    9139604

   volume_open related_ec_event_id related_news_items  start_timestamp split  \
0      9004498                None               None       1581483300  None

  dividend related_patterns_high related_patterns_med
0     None                  None                 None

KeyboardInterrupt: